Reworked Shooter Controls
cachemoney8096/2022-rapid-react pull request #12
Opened 2022-10-01 22:20 UTC by tails618

Slightly adjusted the way shooting/ending shooting works. May not actually work yet.

2022-10-01 22:30 UTC, tails618 commented
@balghane I added that if statement logic to the `initialize()` function in the shooter.

2022-10-01 23:01 UTC, balghane commented on src/main/java/frc/robot/command/ShootBalls.java
> +  private static boolean shootOn;
This should not be static I don't think

2022-10-03 14:34 UTC, tails618 commented on src/main/java/frc/robot/command/ShootBalls.java
> +  private static boolean shootOn;
Fixed.

2022-10-04 01:29 UTC, balghane reviewed
Looks good, pending testing on the robot

2022-10-08 21:00 UTC, tails618 commented
Shooter works + commented out most prints + removed intake limits (again)

2022-10-08 21:03 UTC, balghane requested changes

2022-10-08 21:03 UTC, balghane commented on src/main/java/frc/robot/command/ShootBalls.java
> +    System.out.println("CONSTRUCTOR");
Can you remove all these prints now that we don't need them anymore

2022-10-08 21:03 UTC, balghane commented on src/main/java/frc/robot/subsystems/Intake.java
> +>>>>>>> shooter-controls
Fix this conflict

2022-10-08 21:18 UTC, balghane approved these changes

2022-10-08 21:18 UTC, merged